version: '3'
output: 'prefixed'

tasks:
  default:
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: docs

  action:
    cmds:
      - task: lint
      - task: test

  fmt:
    cmds:
      - go fix ./...

  lint:
    cmds:
      - go vet ./...
      - task: gosec
      - task: staticcheck

  test:
    cmds:
      - go test -cover -coverprofile=coverage.out ./...

  docs:
    cmds:
      - task: gomarkdoc
      - task: markdownfmt

  revive:
    vars:
      CONFIG: revive.toml
    preconditions:
      - test -f "{{.CONFIG}}"
    cmds:
      - (command -v revive) || go install github.com/mgechev/revive@v1.3.4
      - revive -config=revive.toml ./...

  staticcheck:
    cmds:
      - (command -v staticcheck) || go install honnef.co/go/tools/cmd/staticcheck@latest
      - staticcheck ./...

  gomarkdoc:
    cmds:
      - (command -v gomarkdoc) || go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
      - gomarkdoc ./...

  gosec:
    cmds:
      - (command -v gosec) || go install github.com/securego/gosec/v2/cmd/gosec@latest
      - gosec ./...

  markdownfmt:
    cmds:
      - (command -v markdownfmt) || go install github.com/shurcooL/markdownfmt@latest
      - markdownfmt -w README.md
